export default {
    FETCHED_CHARACTERS: 'FETCHED_CHARACTERS',
    FETCHED_CHARACTER: 'FETCHED_CHARACTER',
    REMOVE_CHARACTER: 'REMOVE_CHARACTER',
    SELECT_CHARACTER: 'SELECT_CHARACTER',
    UPDATE_CHARACTER: 'UPDATE_CHARACTER',
}
